# Generated by Django 5.2.1 on 2025-06-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product', max_length=255)),
                ('sku', models.CharField(help_text='Stock Keeping Unit, must be unique', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product', max_digits=10)),
                ('inventory_quantity', models.PositiveIntegerField(default=0, help_text='Current stock quantity')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update to this product')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['sku'], name='shopify_app_sku_fe40f6_idx'), models.Index(fields=['name'], name='shopify_app_name_6a94ed_idx'), models.Index(fields=['last_updated'], name='shopify_app_last_up_b75634_idx'), models.Index(fields=['price'], name='shopify_app_price_eef9ff_idx'), models.Index(fields=['inventory_quantity'], name='shopify_app_invento_1c52b5_idx')],
            },
        ),
    ]
